# Generated by Django 5.2 on 2025-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('imp_exp_number', models.CharField(max_length=100)),
            ],
        ),
    ]
